language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "3.2"
  - "3.1"
install:
  - "pip install ."
  - "pip install -r requirements.txt"
script:
  - export TIMETRACKER_APP_ENVIRONMENT="test"
  - pytest
after_success: coveralls
